### ISSUE TITLE
Missing build instructions

### ISSUE THREAD

**Issue by nyanpasu64** [ZorroTrackerDev/ZorroTracker#7]
The README doesn't have instructions on how to build the program.

EDIT: https://github.com/ZorroTrackerDev/ZorroTracker/issues/8#issuecomment-864300164:

> You need to pull the submodules along with the main module. [`git clone --recursive`](https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules) for example does this (and some git clients allow you to do so manually too)

I tried looking at https://github.com/ZorroTrackerDev/ZorroTracker/blob/main/.github/workflows/node.js.yml to see what it did. It seems to run `npm install` (dependencies, not the app) followed by `npm run ci_init` (which according to `npm run`'s help output, aliases to `npm run build`). This calls `npm run copy` which puts files in the "build" folder. At this point, `npm run electron` works. (I didn't try `npm run ci_deploy = electron-builder build --publish never` yet.)

If this is the intended build procedure, I think it should be documented somewhere, such as the README.

**Comment by freq-mod** [comment]
`npm install`+ `npm run build` + `npm run pack` works well enough, while being much shorter

**Comment by Awuwunya** [comment]
I've added some documentation in 17bf1b28cdbf040ab10553c2318bdc9d995d6915. This of course needs to be filled with more information, should any need adding.
